/**
 * AqlSampling.js — ISO 2859-1 / ANSI-ASQ Z1.4 single sampling, normal severity.
 *
 * Shared by IQC and IPQC. Pure functions (no SpreadsheetApp) so they are
 * unit-testable in isolation.
 *
 *   getSamplingPlan(lotSize, aql, level)  -> { codeLetter, sampleSize, ac, re, ... }
 *   verdict(defects, ac, re)              -> 'ACCEPT' | 'REJECT'
 *
 * Reference: ISO 2859-1 Table 1 (sample-size code letters) and Table 2-A
 * (single sampling plans for normal inspection).
 */

// ── Table 1: lot size → code letter, by general inspection level ──────────────
// Rows are [lotMin, lotMax, {S1..S4, I, II, III}]. We support general levels I/II/III.
var AQL_CODE_TABLE_ = [
  [2, 8,          { I: 'A', II: 'A', III: 'B' }],
  [9, 15,         { I: 'A', II: 'B', III: 'C' }],
  [16, 25,        { I: 'B', II: 'C', III: 'D' }],
  [26, 50,        { I: 'C', II: 'D', III: 'E' }],
  [51, 90,        { I: 'C', II: 'E', III: 'F' }],
  [91, 150,       { I: 'D', II: 'F', III: 'G' }],
  [151, 280,      { I: 'E', II: 'G', III: 'H' }],
  [281, 500,      { I: 'F', II: 'H', III: 'J' }],
  [501, 1200,     { I: 'G', II: 'J', III: 'K' }],
  [1201, 3200,    { I: 'H', II: 'K', III: 'L' }],
  [3201, 10000,   { I: 'J', II: 'L', III: 'M' }],
  [10001, 35000,  { I: 'K', II: 'M', III: 'N' }],
  [35001, 150000, { I: 'L', II: 'N', III: 'P' }],
  [150001, 500000,{ I: 'M', II: 'P', III: 'Q' }],
  [500001, Infinity, { I: 'N', II: 'Q', III: 'R' }]
];

// ── Sample size per code letter (Table 2-A, first column) ─────────────────────
var AQL_SAMPLE_SIZE_ = {
  A: 2, B: 3, C: 5, D: 8, E: 13, F: 20, G: 32, H: 50, J: 80,
  K: 125, L: 200, M: 315, N: 500, P: 800, Q: 1250, R: 2000
};

// Code-letter order, used to resolve arrows (↓ = next letter down / larger sample,
// ↑ = next letter up / smaller sample) when a cell has no own plan.
var AQL_LETTERS_ = ['A','B','C','D','E','F','G','H','J','K','L','M','N','P','Q','R'];

// ── Table 2-A: Ac/Re, normal single sampling. ────────────────────────────────
// ANSI/ASQ Z1.4 (= ISO 2859-1) Table II-A is a single diagonal: acceptance numbers
// step along the ladder [0,1,2,3,5,7,10,14,21,...], advancing by one step for each
// step DOWN in code letter (larger sample) OR each step RIGHT in AQL. So the whole
// table is generated by one formula instead of 96 hand-typed cells (which is where
// transcription errors creep in). Ac = LADDER[ letterIndex + aqlIndex - 7 ]; below the
// ladder start it's an arrow-up (smaller sample), above the end an arrow-down (larger).
// Re = Ac + 1 always. Verified against published bedrock values (J/2.5→5·6, L/1.5→7·8,
// K/2.5→7·8, G/2.5→2·3, H/4.0→5·6, …) in the unit tests below.
var AQL_LADDER_ = [0, 1, 2, 3, 5, 7, 10, 14, 21, 30, 44]; // Ac series (R5 rounded)
var AQL_COLS_   = { '0.65': 0, '1.0': 1, '1.5': 2, '2.5': 3, '4.0': 4, '6.5': 5 };
var AQL_DIAG_OFFSET_ = 7; // solved from J(idx8)/2.5(idx3) → Ac 5 (ladder idx 4)

// Normalize an AQL input ('AQL 2.5', '2.5', 2.5) to the table key '2.5'.
function normalizeAql_(aql) {
  var s = String(aql).replace(/aql/i, '').trim();
  var n = parseFloat(s);
  if (isNaN(n)) return null;
  // Map to the canonical string key (avoids 1 vs 1.0 mismatch).
  var keyMap = { '0.65': '0.65', '1': '1.0', '1.0': '1.0', '1.5': '1.5',
                 '2.5': '2.5', '4': '4.0', '4.0': '4.0', '6.5': '6.5' };
  return keyMap[String(n)] || keyMap[s] || null;
}

function codeLetterFor_(lotSize, level) {
  var lvl = (level || 'II').toString().toUpperCase().replace(/[^IVS0-9]/g, '') || 'II';
  if (lvl !== 'I' && lvl !== 'II' && lvl !== 'III') lvl = 'II';
  for (var i = 0; i < AQL_CODE_TABLE_.length; i++) {
    var row = AQL_CODE_TABLE_[i];
    if (lotSize >= row[0] && lotSize <= row[1]) return row[2][lvl];
  }
  return null;
}

// Resolve the plan via the diagonal formula, following arrows off the ladder edges.
// Arrow-down (idx past ladder end) = step to the next larger code letter; arrow-up
// (idx below 0) = step to the next smaller code letter. Both keep the same Ac ladder
// position, so we walk letters until the cell lands on a real ladder value.
function resolvePlan_(letter, aqlKey) {
  var li = AQL_LETTERS_.indexOf(letter);
  var ai = AQL_COLS_[aqlKey];
  if (li < 0 || ai == null) return null;
  var guard = 0;
  while (li >= 0 && li < AQL_LETTERS_.length && guard++ < 40) {
    var idx = li + ai - AQL_DIAG_OFFSET_;
    if (idx < 0) { li += 1; continue; }                 // arrow up → larger sample letter
    if (idx >= AQL_LADDER_.length) { li -= 1; continue; } // arrow down → smaller sample letter
    var ac = AQL_LADDER_[idx];
    return { letter: AQL_LETTERS_[li], ac: ac, re: ac + 1 };
  }
  return null;
}

/**
 * getSamplingPlan(lotSize, aql, level)
 * @returns { codeLetter, sampleSize, ac, re, lotSize, aql, level, severity, sampling }
 *          or { error } when inputs are invalid.
 */
function getSamplingPlan(lotSize, aql, level) {
  var lot = parseInt(lotSize, 10);
  if (!lot || lot < 2) return { error: 'Enter a lot size of at least 2.' };
  var aqlKey = normalizeAql_(aql);
  if (!aqlKey) return { error: 'Unsupported AQL: ' + aql };
  var startLetter = codeLetterFor_(lot, level);
  if (!startLetter) return { error: 'No code letter for lot size ' + lot };
  var plan = resolvePlan_(startLetter, aqlKey);
  if (!plan) return { error: 'No sampling plan for ' + startLetter + ' @ AQL ' + aqlKey };
  var sampleSize = AQL_SAMPLE_SIZE_[plan.letter];
  // Per the standard: if the code-letter sample size meets or exceeds the lot, inspect
  // 100% — you can't pull 50 from a lot of 20.
  if (sampleSize >= lot) {
    return {
      codeLetter: plan.letter, sampleSize: lot, ac: plan.ac, re: plan.re,
      lotSize: lot, aql: aqlKey, level: (level || 'II'),
      severity: 'normal', sampling: '100%'
    };
  }
  return {
    codeLetter: plan.letter,
    sampleSize: sampleSize,
    ac: plan.ac,
    re: plan.re,
    lotSize: lot,
    aql: aqlKey,
    level: (level || 'II'),
    severity: 'normal',
    sampling: 'single'
  };
}

/** verdict(defects, ac, re) -> 'ACCEPT' | 'REJECT' */
function verdict(defects, ac, re) {
  var d = parseInt(defects, 10);
  if (isNaN(d) || d < 0) d = 0;
  if (d <= ac) return 'ACCEPT';
  if (d >= re) return 'REJECT';
  return 'ACCEPT'; // between Ac and Re can't happen for single sampling (re = ac+1)
}

/**
 * _testAqlSampling — assertions against published ANSI/ASQ Z1.4 bedrock values.
 * Run via `clasp run _testAqlSampling`. Returns { pass, fail, results }.
 */
function _testAqlSampling() {
  var cases = [
    // lot, aql, level, expCode, expN, expAc, expRe
    [1000, '2.5', 'II', 'J', 80, 5, 6],
    [1000, '1.5', 'II', 'J', 80, 3, 4],
    [1000, '4.0', 'II', 'J', 80, 7, 8],
    [3200, '1.5', 'II', 'K', 125, 5, 6],
    [3200, '2.5', 'II', 'K', 125, 7, 8],
    [5000, '1.5', 'II', 'L', 200, 7, 8],
    [5000, '2.5', 'II', 'L', 200, 10, 11],
    [150,  '2.5', 'II', 'F', 20, 1, 2],
    [500,  '2.5', 'II', 'H', 50, 3, 4],
    [500,  '4.0', 'II', 'H', 50, 5, 6],
    [280,  '1.0', 'II', 'G', 32, 1, 2],
    [35000,'1.0', 'II', 'N', 500, 10, 11]
  ];
  var results = [], pass = 0, fail = 0;
  cases.forEach(function(c) {
    var p = getSamplingPlan(c[0], c[1], c[2]);
    var ok = !p.error && p.codeLetter === c[3] && p.sampleSize === c[4] && p.ac === c[5] && p.re === c[6];
    if (ok) pass++; else fail++;
    results.push((ok ? 'PASS ' : 'FAIL ') + 'lot' + c[0] + ' AQL' + c[1] +
      ' => ' + (p.error || (p.codeLetter + ' n=' + p.sampleSize + ' ' + p.ac + '/' + p.re)) +
      (ok ? '' : ' [want ' + c[3] + ' n=' + c[4] + ' ' + c[5] + '/' + c[6] + ']'));
  });
  // verdict logic
  var v = (verdict(2,5,6) === 'ACCEPT' && verdict(6,5,6) === 'REJECT' && verdict(5,5,6) === 'ACCEPT');
  if (v) pass++; else { fail++; results.push('FAIL verdict logic'); }
  return { pass: pass, fail: fail, results: results };
}
